version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "4000:4000"
  backend:
    image: tomcat:9.0
    deploy:
      replicas: 3
    expose:
      - "8080"
    volumes:
      - './local-project/target/devflection-local-project.war:/usr/local/tomcat/webapps/app.war'